/*!
    \copyright Copyright (c) 2024 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The av marshal type declarations. This file is generated by C:/qtil/QCC3044/qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-master-ORG/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _AV_MARSHAL_TYPEDEF_H__
#define _AV_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <task_list.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_avInstanceTaskData;

#define AV_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(avInstanceTaskData)

#endif /* _AV_MARSHAL_TYPEDEF_H__ */

