/*!
    \copyright Copyright (c) 2024 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_va_mic_1mic.h
    \brief The chain_va_mic_1mic chain.

    This file is generated by C:\qtil\QCC3044\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-master-ORG\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_VA_MIC_1MIC_H__
#define _CHAIN_VA_MIC_1MIC_H__

/*!
\page chain_va_mic_1mic
    @startuml
        object OPR_MIC_GAIN
        OPR_MIC_GAIN : id = CAP_ID_BASIC_PASS
        object EPR_VA_MIC_MIC1_IN #lightgreen
        OPR_MIC_GAIN "IN(0)" <-- EPR_VA_MIC_MIC1_IN
        object EPR_VA_MIC_ENCODE_OUT #lightblue
        EPR_VA_MIC_ENCODE_OUT <-- "OUT(0)" OPR_MIC_GAIN
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_va_mic_1mic_config;

#endif /* _CHAIN_VA_MIC_1MIC_H__ */

